import org.apache.tools.ant.taskdefs.condition.Os

plugins {
    id 'application'
}

apply from: 'versions.gradle'

group 'ru.mipt.bit'
version '1.0-SNAPSHOT'

application {
    mainClassName = 'ru.mipt.bit.platformer.GameDesktopLauncher'
    if (Os.isFamily(Os.FAMILY_MAC)) {
        applicationDefaultJvmArgs = ['-XstartOnFirstThread']
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "com.badlogicgames.gdx:gdx:1.12.0"
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:1.12.0"
    implementation "com.badlogicgames.gdx:gdx-platform:1.12.0:natives-desktop"

    implementation "org.lwjgl:lwjgl:3.3.3"
    implementation "org.lwjgl:lwjgl-glfw:3.3.3"
    implementation "org.lwjgl:lwjgl-opengl:3.3.3"

    runtimeOnly "org.lwjgl:lwjgl:3.3.3:natives-macos-arm64"
    runtimeOnly "org.lwjgl:lwjgl-glfw:3.3.3:natives-macos-arm64"
    runtimeOnly "org.lwjgl:lwjgl-opengl:3.3.3:natives-macos-arm64"

    implementation "org.lwjgl:lwjgl-openal:3.3.3"
    runtimeOnly "org.lwjgl:lwjgl-openal:3.3.3:natives-macos-arm64"
}
